[package]
name = "irust_api"
version = "0.30.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2021"
description = "IRust API"
repository = "https://github.com/sigmaSd/IRust/tree/master/crates/irust_api"
license = "MIT"

[dependencies]
crossterm = { version = "0.22.1", features = ["serde"] }
rscript = "0.17.0"
serde = { version = "1.0.126", features = ["derive"] }
