[package]
name = "irust"
version = "1.47.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2021"
readme = "README.md"
description = "Cross Platform Rust Repl"
repository = "https://github.com/sigmaSd/IRust"
license = "MIT"

[dependencies]
crossterm = { version = "0.22.1", features = ["serde"] }
dirs = "4.0.0"
toml = "0.5.8"
serde = { version = "1.0.126", features = ["derive"] }
printer = { path = "../printer/", version = "0.4.1" }
irust_api = { path = "../irust_api/", version = "0.29.0" }
irust_repl = { path = "../irust_repl", version = "0.15.0", features = ["serde"] }
rscript = "0.15.0"
rustc_lexer = { version = "727.0.0", package = "rustc-ap-rustc_lexer" }

[target.'cfg(unix)'.dependencies]
nix = "0.23.0"

# flamegraph
# [profile.release]
# debug = true
