[package]
name = "fun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
irust_api = { path = "../../crates/irust_api" }
rscript = "0.17.0"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
